# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friends',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='friends',
            name='birthplace',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='friends',
            name='company',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='friends',
            name='couple',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='friends',
            name='development',
            field=models.CharField(default='无', max_length=500),
        ),
        migrations.AlterField(
            model_name='friends',
            name='email',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='friends',
            name='face',
            field=models.CharField(default='无', max_length=500),
        ),
        migrations.AlterField(
            model_name='friends',
            name='interest',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='friends',
            name='marriage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friends',
            name='nickname',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='friends',
            name='phone',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='friends',
            name='politic',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='friends',
            name='position',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='friends',
            name='qualification',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='friends',
            name='record',
            field=models.CharField(default='无', max_length=500),
        ),
        migrations.AlterField(
            model_name='friends',
            name='relation',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='friends',
            name='remark',
            field=models.CharField(default='无', max_length=500),
        ),
        migrations.AlterField(
            model_name='friends',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friends',
            name='sex',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='friends',
            name='skill',
            field=models.CharField(default='无', max_length=50),
        ),
    ]
