# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20171104_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='tag',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
